# keyd config for Nami platform Chromebooks
# (Acer Chromebook 13, Dell Chromebook 13, HP Chromebook x360 14, etc.)

[ids]
*

[main]
back           = f1
forward        = f2
refresh        = f3
fullscreen     = f4
display_toggle = f5
brightness_down = f6
brightness_up  = f7
mute           = f8
volume_down    = f9
volume_up      = f10

capslock = esc
search   = super

[alt]
back           = previoussong
forward        = nextsong
refresh        = stopcd
fullscreen     = playpause
display_toggle = f5
brightness_down = kbdillumdown
brightness_up  = kbdillumup
mute           = mute
volume_down    = volumedown
volume_up      = volumeup
