# CobaltOS libinput touchpad quirks for ATLAS (Pixelbook Go)
# Glass clickpad — 120mm × 67mm.

[Pixelbook Go Touchpad]
MatchUdevType=touchpad
MatchBus=i2c
ModelChromebook=1
AttrTouchSizeRange=22:10
AttrPalmSizeThreshold=22
AttrSizeHint=120x67
