# CobaltOS libinput touchpad quirks for EVE (Google Pixelbook)
# Large glass clickpad — 133mm × 73mm, very precise.

[Pixelbook Touchpad]
MatchUdevType=touchpad
MatchBus=i2c
MatchVendor=0x06CB
ModelChromebook=1
AttrTouchSizeRange=25:12
AttrPalmSizeThreshold=25
AttrSizeHint=133x73
