# CobaltOS libinput touchpad quirks for NAMI (HP / Dell Chromebook)
# Standard buttonless i2c touchpad.

[Nami Touchpad]
MatchUdevType=touchpad
MatchBus=i2c
ModelChromebook=1
AttrTouchSizeRange=20:10
AttrPalmSizeThreshold=20
