# EVE HiFi Use Case
# Google Pixelbook — Intel SOF audio

SectionVerb {
    Value {
        PlaybackPCM "hw:sofglkda7219max,0"
        CapturePCM  "hw:sofglkda7219max,0"
    }

    EnableSequence [
        cset "name='Headphone Playback Switch' on"
        cset "name='Speaker Playback Switch' on"
    ]

    DisableSequence [
        cset "name='Headphone Playback Switch' off"
        cset "name='Speaker Playback Switch' off"
    ]
}

SectionDevice."Speaker" {
    Comment "Internal Speakers"
    Value {
        PlaybackChannels 2
    }
}

SectionDevice."Headphones" {
    Comment "Headphone Jack"
    Value {
        PlaybackChannels 2
        JackControl "Headphone Jack"
    }
}
