# Generic HDA HiFi Use Case

SectionVerb {
    Value {
        PlaybackPCM "hw:0,0"
        CapturePCM  "hw:0,0"
    }

    EnableSequence [
        cset "name='Headphone Playback Switch' on"
        cset "name='Master Playback Switch' on"
    ]

    DisableSequence [
        cset "name='Headphone Playback Switch' off"
        cset "name='Master Playback Switch' off"
    ]
}

SectionDevice."Speaker" {
    Comment "Speaker"
    Value { PlaybackChannels 2 }
}

SectionDevice."Headphones" {
    Comment "Headphone Jack"
    Value {
        PlaybackChannels 2
        JackControl "Headphone Jack"
    }
}
