# Nami platform UCM2 profile
# Covers: Acer CB 13 (AKALI), Dell CB 13 (VAYNE), HP x360 14 (DRATINI)
# Platform: Intel Coffee Lake, SOF audio

SectionUseCase."HiFi" {
    File "HiFi.conf"
    Comment "HiFi quality Music Playback"
}
